DB_HOST = "localhost";
DB_USER = "root";
DB_PASSWORD = "";
DB_DATABASE = "";
PORT = 8000;
SECRET_KEY = "your_secret_key";
BASE_URL = "http://localhost:8000";
FRONTEND_BASE_URL="http://localhost:3000"
EMAIL_ADDRESS = "";
EMAIL_PASSWORD = "";